name: github-docker

on:
  push:
    branches:
      - 'docker*'
      - 'master'

permissions:
  contents: read
  packages: write

jobs:
  build-master-docker:
    name: build master docker ${{ matrix.ubuntu_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [focal, jammy]
        # Use 2 jobs to build, but only 1 for the focal image
        # as it starves the github machine for memory.
        include:
          - n_jobs: 2
          - n_jobs: 1
            ubuntu_version: focal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image of master ${{ matrix.ubuntu_version }}
        uses: docker/build-push-action@v5
        with:
          context: ./contrib/docker/
          cache-from: type=registry,ref=dealii/dependencies:${{ matrix.ubuntu_version }}
          cache-to: type=inline
          build-args: |
            IMG=${{ matrix.ubuntu_version }}
            NJOBS=${{ matrix.n_jobs }}
            VER=master
          push: ${{ github.ref_name == 'master' }}
          tags: dealii/dealii:master-${{ matrix.ubuntu_version }}
